config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :concerts
    resources :crews
  end
  root "groups#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :group
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :gender, presence: true
  
  has_many :concerts, dependent: :destroy
  has_many :crews, inverse_of: :group, dependent: :destroy
  accepts_nested_attributes_for :crews, reject_if: :all_blank, allow_destroy: true

  enum gender: { hombres: 0, mujeres: 1, banda: 2 }

  def concertcount
    self.concerts.count
  end

  def crewcount
    self.crews.count
  end

  def attendantcount
    self.concerts.pluck(:attendants).sum
  end

  def debutdate
    if self.concerts.any?
      self.concerts.order(date: :asc).first.date
    else
      "No ha debutado"
    end
  end

  def monthconcert
    self.concerts.where('extract(year from date) = ?', Time.now.year).where('extract(month from date) = ?', Time.now.month).count
  end

  def last_concert
    if self.concerts.any?
      self.concerts.order(date: :asc).last.date.strftime("%Y-%B-%A")
    else
      "No ha debutado"
    end
  end

  def max_attendants
    if self.concerts.any?
      self.concerts.pluck(:attendants).max
    else
      "No ha debutado"
    end
  end

  def max_length
    if self.concerts.any?
      self.concerts.pluck(:length).max
    else
      "No ha debutado"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @group = Group.find(params[:group_id])
    @concerts = @group.concerts
  end

  # GET /concerts/1 or /concerts/1.json
  def show
    @group = Group.find(params[:group_id])
    @concert = Concert.find(params[:id])
  end

  # GET /concerts/new
  def new
    @group = Group.find(params[:group_id])
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
    @group = Group.find(params[:group_id])
    @concert = Concert.find(params[:id])
  end

  # POST /concerts or /concerts.json
  def create
    @group = Group.find(params[:group_id])
    @concert = Concert.new(concert_params)
    @concert.group = @group

    respond_to do |format|
      if @concert.save
        format.html { redirect_to group_concert_path(@group, @concert), notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    @group = Group.find(params[:group_id])
    @concert = Concert.find(params[:id])
    respond_to do |format|
      if @concert.update(concert_params.merge(group: @group))
        format.html { redirect_to group_concert_path(@group, @concert), notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to group_concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:date, :length, :attendants)
    end
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /crews or /crews.json
  def index
    @group = Group.find(params[:group_id])
    @crews = @group.crews
  end

  # GET /crews/1 or /crews/1.json
  def show
    @group = Group.find(params[:group_id])
    @crew = Crew.find(params[:id])
  end

  # GET /crews/new
  def new
    @group = Group.find(params[:group_id])
    @crew = Crew.new
  end

  # GET /crews/1/edit
  def edit
    @group = Group.find(params[:group_id])
    @crew = Crew.find(params[:id])
  end

  # POST /crews or /crews.json
  def create
    @group = Group.find(params[:group_id])
    @crew = Crew.new(crew_params)
    @crew.group = @group

    respond_to do |format|
      if @crew.save
        format.html { redirect_to group_crew_path(@group, @crew), notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: @crew }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crews/1 or /crews/1.json
  def update
    @group = Group.find(params[:group_id])
    @crew = Crew.find(params[:id])
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to group_crew_path(@group, @crew), notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: @crew }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crews/1 or /crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to group_crews_url, notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew
      @crew = Crew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(:name)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.crews.build
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :gender, crews_attributes:[:id, :name, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/concerts/_form.html.erb
<%= form_with(model: [@group, concert], local: true) do |form| %>
  <% if concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
      <% concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date, "Fecha" %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :length, "Duracion (Minutos)" %>
    <%= form.number_field :length %>
  </div>

  <div class="field">
    <%= form.label :attendants, "Asistentes" %>
    <%= form.number_field :attendants %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editar concierto de <%= @group.name %></h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Show', group_concerts_path(@group, @concert) %> |
<%= link_to 'Volver', group_concerts_path(@group) %>

app/views/concerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conciertos de <%= @group.name %></h1>


<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>Fecha</th>
      <th>Duracion (Minutos)</th>
      <th>Asistentes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concerts.each do |concert| %>
      <tr>
        <td><%= concert.date %></td>
        <td><%= concert.length %></td>
        <td><%= concert.attendants %></td>
        <td><%= link_to 'Show', group_concert_path(@group, concert) %></td>
        <td><%= link_to 'Edit', edit_group_concert_path(@group, concert) %></td>
        <td><%= link_to 'Destroy', group_concert_path(@group, concert), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo concierto', new_group_concert_path(@group) %>
<%= link_to 'Volver', groups_path %>

app/views/concerts/new.html.erb
<h1>Crear concierto para <%= @group.name %></h1>

<%= render 'form', concert: @concert %>

<%= link_to 'Volver', group_concerts_path(@group) %>

app/views/concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @concert.date %>
</p>

<p>
  <strong>Duracion (Minutos):</strong>
  <%= @concert.length %>
</p>

<p>
  <strong>Asistentes:</strong>
  <%= @concert.attendants %>
</p>

<p>
  <strong>Grupo:</strong>
  <%= @concert.group.name %>
</p>

<%= link_to 'Editar', edit_group_concert_path(@group, @concert) %> |
<%= link_to 'Volver', group_concerts_path(@group) %>

app/views/crews/_form.html.erb
<%= form_with(model: [@group, crew], local: true) do |form| %>
  <% if crew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew.errors.count, "error") %> prohibited this crew from being saved:</h2>

      <ul>
      <% crew.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crews/edit.html.erb
<h1>Editing Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Show', group_crews_path(@group, @crew) %> |
<%= link_to 'Back', group_crews_path(@group) %>

app/views/crews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crews</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crews.each do |crew| %>
      <tr>
        <td><%= crew.name %></td>
        <td><%= crew.group.name %></td>
        <td><%= link_to 'Show', group_crew_path(@group, crew) %></td>
        <td><%= link_to 'Edit', edit_group_crew_path(@group, crew) %></td>
        <td><%= link_to 'Destroy', group_crew_path(@group, crew), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew', new_group_crew_path(@group) %>
<%= link_to 'Volver', groups_path %>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form', crew: @crew %>

<%= link_to 'Back', group_crews_path(@group) %>

app/views/crews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @crew.name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @crew.group.name %>
</p>

<%= link_to 'Edit', edit_group_crew_path(@group, @crew) %> |
<%= link_to 'Back', group_crews_path(@group) %>

app/views/groups/_crew_fields.html.erb
<div class='nested-fields'>
    <div class="field">
      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>
      <%= link_to_remove_association "Remover integrante", f %>
    </div>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender, "Genero" %>
    <%= form.select :gender, Group.genders.keys %>
  </div>

  <h3>Integrantes</h3>
  <div id='crews'>
    <%= form.fields_for :crews do |crew| %>
      <%= render 'crew_fields', :f => crew %>
    <% end %>
    <div class='links'>
      <br>
      <%= link_to_add_association 'Agregar integrante', form, :crews %>
    </div>
  </div>

  <div class="actions">
    <br>
    <%= form.submit "Enviar" %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Volver', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grupos</h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Debut</th>
      <th>Genero</th>
      <th>N° de integrantes</th>
      <th>Integrantes</th>
      <th>Conciertos</th>
      <th>Total de asistentes</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.debutdate %></td>
        <td><%= group.gender %></td>
        <td><%= group.crewcount %></td>
        <td>
          <% group.crews.each do |crew| %>
            <ul>
              <li><%= crew.name %></li>
            </ul>
          <% end %>
        </td>
        <td><%= group.concertcount %></td>
        <td><%= group.attendantcount %></td>
        <td><%= link_to 'Concerts', group_concerts_path(group.id) %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Volver', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>N° de integrantes:</strong>
  <%= @group.crewcount %>
</p>

<p>
  <strong>Debut:</strong>
  <%= @group.debutdate %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @group.gender %>
</p>

<p>
  <strong>Conciertos este mes:</strong>
  <%= @group.monthconcert %>
</p>

<p>
  <strong>Ultimo concierto:</strong>
  <%= @group.last_concert %>
</p>

<p>
  <strong>Numero maximo de asistentes en un concierto:</strong>
  <%= @group.max_attendants %>
</p>

<p>
  <strong>Duracion maxima de un concierto:</strong>
  <%= @group.max_length %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Volver', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>